-- MySQL Script generated by MySQL Workbench
-- Wed Dec 31 13:07:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery` DEFAULT CHARACTER SET utf8 ;
USE `delivery` ;

-- -----------------------------------------------------
-- Table `delivery`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(60) NOT NULL,
  `dataNasc` DATETIME NOT NULL,
  `documento` VARCHAR(14) NOT NULL,
  `email` VARCHAR(140) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `deviceToken` VARCHAR(255) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  `dtUpdated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_premissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_premissoes` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_usuario_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_usuario_permissao` (
  `id` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `IdPemissao` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_usuario_permissao_tb_usuarios_idx` (`idUsuario` ASC),
  INDEX `fk_tb_usuario_permissao_tb_premissoes1_idx` (`IdPemissao` ASC) ,
  CONSTRAINT `fk_tb_usuario_permissao_tb_usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `delivery`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_permissao_tb_premissoes1`
    FOREIGN KEY (`IdPemissao`)
    REFERENCES `delivery`.`tb_premissoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_estabelecimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_estabelecimentos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(11) NULL,
  `descricao` VARCHAR(150) NULL,
  `imagemUrl` VARCHAR(255) NULL,
  `latitude` VARCHAR(15) NOT NULL,
  `longitude` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `enderecoNumero` VARCHAR(6) NOT NULL,
  `enderecoOpicional` VARCHAR(15) NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  `dtUpdated` DATETIME NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_estabelecimentos_tb_usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_tb_estabelecimentos_tb_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `delivery`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_categoria` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(110) NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  `dtUpdated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_produtos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  `dtUpdated` DATETIME NULL,
  `idCategoria` INT NOT NULL,
  `idEstabelecimento` INT NOT NULL,
  `table1_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produtos_tb_categoria1_idx` (`idCategoria` ASC) ,
  INDEX `fk_tb_produtos_tb_estabelecimentos1_idx` (`idEstabelecimento` ASC) ,
  CONSTRAINT `fk_tb_produtos_tb_categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `delivery`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_tb_estabelecimentos1`
    FOREIGN KEY (`idEstabelecimento`)
    REFERENCES `delivery`.`tb_estabelecimentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`tb_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_vendas` (
  `id` INT NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  `dtUpdated` DATETIME NULL,
  `idUsuario` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table1_tb_usuarios1_idx` (`idUsuario` ASC) ,
  INDEX `fk_table1_tb_produtos1_idx` (`idProduto` ASC) ,
  CONSTRAINT `fk_table1_tb_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `delivery`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_tb_produtos1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `delivery`.`tb_produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`id_push`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`tb_push` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(120) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  `idUsuarios` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_push_tb_usuarios1_idx` (`idUsuarios` ASC) ,
  CONSTRAINT `fk_id_push_tb_usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `delivery`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
