version: "3.3"
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      # MYSQL_DATABASE: "dart"
      MYSQL_USER: "database"
      MYSQL_PASSWORD: "dart_pass"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
      - "./database.sql:/docker-entrypoint-initdb.d/database.sql"
